name: 'upstream version action'
description: 'finds the upstream version of a manjaro package'

inputs:
  name:
    description: 'name of the package to check'
    required: true

outputs:
  aarch64_unstable:
    description: the upstream version
    value: ${{ steps.info.outputs.aarch64_unstable }}
  aarch64_testing:
    description: the upstream version
    value: ${{ steps.info.outputs.aarch64_testing }}
  aarch64_stable:
    description: the upstream version
    value: ${{ steps.info.outputs.aarch64_stable }}
  x86_64_unstable:
    description: the upstream version
    value: ${{ steps.info.outputs.x64_64_unstable }}
  x86_64_testing:
    description: the upstream version
    value: ${{ steps.info.outputs.x64_64_testing }}
  x86_64_stable:
    description: the upstream version
    value: ${{ steps.info.outputs.x64_64_stable }}

runs:
  using: "composite"
  steps:
    - name: get info
      id: info
      shell: bash
      run: |
        for arch in x86_64 aarch64; do
          for branch in unstable testing stable; do
            url="https://search.manjaro-sway.download/?name=${{ inputs.name }}&branch=${branch}&arch=${arch}"
            echo $url
            echo "${arch}_${branch}=$(curl -s $url | jq -r '.version | sub(":";"__")')" >>$GITHUB_OUTPUT
          done
        done
